import re
import os

files_to_process = [
    {
        "src": r"c:\Users\alecy\Desktop\coding\AlessandroBonomo28.github.io\_posts\2023-07-19-Scrivere-un-3d-engine-da-zero-tutorial-5.md",
        "dst": r"c:\Users\alecy\Desktop\coding\AlessandroBonomo28.github.io\_posts\2023-07-19-Scrivere-un-3d-engine-da-zero-tutorial-5-en.md",
        "replacements": [
            (r"lang: it", r"lang: en"),
            (r"lang_ref: 3d-engine-5", r"lang_ref: 3d-engine-5\npermalink: /en/posts/Scrivere-un-3d-engine-da-zero-tutorial-5/"),
            (r"alt: Camera e navigazione 3D in p5.js", r"alt: Camera and 3D navigation in p5.js"),
            (r"# Camera e Navigazione 3D in p5.js - 3D Engine Tutorial 5", r"# Camera and 3D Navigation in p5.js - 3D Engine Tutorial 5"),
            (r"## Cosa Facciamo", r"## What We're Doing"),
            (r"In questo tutorial aggiungiamo una \*\*camera controllabile\*\*! Puoi muoverti nello spazio 3D con WASD, guardare in giro trascinando il mouse, e vedere gli assi di riferimento. È come un mini motore 3D first-person!", r"In this tutorial we add a **controllable camera**! You can move around in 3D space with WASD, look around by dragging the mouse, and see the reference axes. It's like a first-person mini 3D engine!"),
            (r"## Il Codice Spiegato", r"## The Code Explained"),
            (r"### Variabili della Camera", r"### Camera Variables"),
            (r"- `cameraYaw`: rotazione orizzontale \(sinistra/destra\)", r"- `cameraYaw`: horizontal rotation (left/right)"),
            (r"- `cameraPitch`: rotazione verticale \(su/giù\)", r"- `cameraPitch`: vertical rotation (up/down)"),
            (r"- `playerPos`: posizione della camera nello spazio", r"- `playerPos`: camera position in space"),
            (r"- `vUp`, `vRight`, `vForward`: gli assi del sistema di coordinate della camera", r"- `vUp`, `vRight`, `vForward`: the axes of the camera coordinate system"),
            (r"### Prodotto Vettoriale", r"### Cross Product"),
            (r"Il prodotto vettoriale genera un vettore perpendicolare a due vettori dati. Lo usiamo per calcolare `vRight` partendo da `vUp` e `vForward`.", r"The cross product generates a vector perpendicular to two given vectors. We use it to calculate `vRight` starting from `vUp` and `vForward`."),
            (r"### Matrice Look-At", r"### Look-At Matrix"),
            (r"Questa matrice trasforma il mondo dal punto di vista della camera. Combina:", r"This matrix transforms the world from the camera's point of view. It combines:"),
            (r"- \*\*Rotazione\*\*: orienta il mondo secondo gli assi della camera", r"- **Rotation**: orients the world according to the camera's axes"),
            (r"- \*\*Traslazione\*\*: sposta il mondo in base alla posizione della camera", r"- **Translation**: moves the world based on the camera's position"),
            (r"### Il Loop Principale", r"### The Main Loop"),
            (r"Ora il flusso è: \*\*Trasformazioni Oggetto → View \(Camera\) → Proiezione\*\*", r"Now the flow is: **Object Transformations → View (Camera) → Projection**"),
            (r"### Controlli Tastiera", r"### Keyboard Controls"),
            (r"Due modalità di movimento:", r"Two movement modes:"),
            (r"- \*\*Assoluta\*\*: WASD muove lungo assi fissi", r"- **Absolute**: WASD moves along fixed axes"),
            (r"- \*\*Relativa\*\*: WASD muove nella direzione in cui guardi \(come nei giochi FPS\)", r"- **Relative**: WASD moves in the direction you are looking (like in FPS games)"),
            (r"### Controlli Mouse", r"### Mouse Controls"),
            (r"Trascinando il mouse:", r"Dragging the mouse:"),
            (r"- Movimento orizzontale → cambia `cameraYaw` \(guardi sinistra/destra\)", r"- Horizontal movement → changes `cameraYaw` (look left/right)"),
            (r"- Movimento verticale → cambia `cameraPitch` \(guardi su/giù\)", r"- Vertical movement → changes `cameraPitch` (look up/down)"),
            (r"- Ricalcola i vettori `vForward`, `vUp`, `vRight` in base alla rotazione", r"- Recalculates `vForward`, `vUp`, `vRight` vectors based on the rotation"),
            (r"### Rendering degli Assi", r"### Axis Rendering"),
            (r"Disegna gli assi X \(rosso\), Y \(verde\), Z \(blu\) partendo dall'origine. Proietta sia l'origine \(0,0,0\) che il punto finale dell'asse \(1,0,0 per X, ecc.\) e li collega con una linea.", r"Draws the X (red), Y (green), Z (blue) axes starting from the origin. Projects both the origin (0,0,0) and the axis end point (1,0,0 for X, etc.) and connects them with a line."),
            (r"### Info HUD", r"### HUD Info"),
            (r"Mostra posizione e rotazione della camera sullo schermo \(converti radianti in gradi\).", r"Shows the camera position and rotation on the screen (convert radians to degrees)."),
            (r"## Concetti Chiave", r"## Key Concepts"),
            (r"### Sistema di Coordinate della Camera", r"### Camera Coordinate System"),
            (r"La camera ha il suo sistema di coordinate:", r"The camera has its own coordinate system:"),
            (r"- \*\*Forward\*\*: dove guardi", r"- **Forward**: where you are looking"),
            (r"- \*\*Up\*\*: sopra la tua testa", r"- **Up**: above your head"),
            (r"- \*\*Right\*\*: alla tua destra \(calcolato con il prodotto vettoriale\)", r"- **Right**: to your right (calculated with the cross product)"),
            (r"### Matrice View", r"### View Matrix"),
            (r"Trasforma il mondo dal punto di vista della camera. È l'inverso delle trasformazioni della camera stessa.", r"Transforms the world from the camera's point of view. It is the inverse of the camera's own transformations."),
            (r"### FPS Controls", r"### FPS Controls"),
            (r"Movimento relativo \+ mouse look = controlli tipici dei giochi first-person!", r"Relative movement + mouse look = typical first-person game controls!"),
            (r"## Provalo", r"## Try It Out"),
            (r"Vai su \[editor.p5js.org\]\(https://editor.p5js.org/\) e:", r"Go to [editor.p5js.org](https://editor.p5js.org/) and:"),
            (r"- \*\*WASD\*\* per muoverti", r"- **WASD** to move"),
            (r"- \*\*Spazio/Shift\*\* per salire/scendere", r"- **Space/Shift** to go up/down"),
            (r"- \*\*Trascina il mouse\*\* per guardare in giro", r"- **Drag the mouse** to look around"),
            (r"- \*\*T\*\* per mostrare/nascondere le coordinate", r"- **T** to show/hide coordinates")
        ]
    },
    {
        "src": r"c:\Users\alecy\Desktop\coding\AlessandroBonomo28.github.io\_posts\2023-07-22-Scrivere-un-3d-engine-da-zero-tutorial-6.md",
        "dst": r"c:\Users\alecy\Desktop\coding\AlessandroBonomo28.github.io\_posts\2023-07-22-Scrivere-un-3d-engine-da-zero-tutorial-6-en.md",
        "replacements": [
            (r"lang: it", r"lang: en"),
            (r"lang_ref: 3d-engine-6", r"lang_ref: 3d-engine-6\npermalink: /en/posts/Scrivere-un-3d-engine-da-zero-tutorial-6/"),
            (r"alt: Triangoli, mesh e illuminazione in p5.js", r"alt: Triangles, meshes and lighting in p5.js"),
            (r"# Triangoli, Mesh e Illuminazione in p5.js", r"# Triangles, Meshes and Lighting in p5.js"),
            (r"## Cosa Facciamo", r"## What We're Doing"),
            (r"In questo tutorial passiamo dai punti ai \*\*triangoli\*\*! Costruiamo un cubo fatto di facce triangolari, calcoliamo le normali per il \*\*back-face culling\*\*, implementiamo l'\*\*illuminazione direzionale\*\*, e ordiniamo i triangoli per profondità. Il risultato è un vero rendering 3D!", r"In this tutorial we move from points to **triangles**! We build a cube made of triangular faces, calculate the normals for **back-face culling**, implement **directional lighting**, and sort the triangles by depth. The result is real 3D rendering!"),
            (r"## Il Codice Spiegato", r"## The Code Explained"),
            (r"### Definizione dei Triangoli", r"### Triangle Definition"),
            (r"Ogni faccia del cubo è divisa in 2 triangoli. Ogni triangolo ha 3 vertici con coordinate \[x, y, z\] in ordine \*\*orario\*\* \(clockwise\). L'ordine è importante per calcolare la normale!", r"Each face of the cube is divided into 2 triangles. Each triangle has 3 vertices with [x, y, z] coordinates in **clockwise** order. The order is important to calculate the normal!"),
            (r"### Direzione della Luce", r"### Light Direction"),
            (r"Vettore che indica da dove viene la luce \(in questo caso dall'asse Z positivo\).", r"Vector that indicates where the light comes from (in this case from the positive Z axis)."),
            (r"### Funzioni Vettoriali", r"### Vector Functions"),
            (r"- \*\*Sottrazione\*\*: calcola il vettore da v2 a v1", r"- **Subtraction**: calculates the vector from v2 to v1"),
            (r"- \*\*Dot product\*\* \(prodotto scalare\): misura quanto due vettori puntano nella stessa direzione", r"- **Dot product**: measures how much two vectors point in the same direction"),
            (r"### Il Loop Principale", r"### The Main Loop"),
            (r"Estraiamo i 3 vertici da ogni triangolo e applichiamo le trasformazioni. `triWorldSpace` contiene ora \[x1,y1,z1, x2,y2,z2, x3,y3,z3\].", r"We extract the 3 vertices from each triangle and apply the transformations. `triWorldSpace` now contains [x1,y1,z1, x2,y2,z2, x3,y3,z3]."),
            (r"### Calcolo della Normale", r"### Normal Calculation"),
            (r"La \*\*normale\*\* è un vettore perpendicolare al triangolo. Si calcola con il prodotto vettoriale di due lati del triangolo. Indica \"verso dove guarda\" la faccia.", r"The **normal** is a vector perpendicular to the triangle. It is calculated with the cross product of two sides of the triangle. It indicates \"where the face is looking\"."),
            (r"### Back-Face Culling", r"### Back-Face Culling"),
            (r"Se la normale del triangolo punta \*\*lontano\*\* dalla camera, il triangolo è invisibile \(stiamo guardando il \"retro\"\). Con il dot product verifichiamo l'angolo: se > 90°, skippiamo il triangolo. Questo ottimizza il rendering!", r"If the triangle's normal points **away** from the camera, the triangle is invisible (we are looking at the \"back\"). With the dot product we verify the angle: if > 90°, we skip the triangle. This optimizes rendering!"),
            (r"### Calcolo dell'Illuminazione", r"### Lighting Calculation"),
            (r"Il dot product tra direzione della luce e normale ci dice quanto il triangolo è illuminato:", r"The dot product between light direction and normal tells us how illuminated the triangle is:"),
            (r"- Paralleli \(dot = 1\) → massima illuminazione", r"- Parallel (dot = 1) → maximum illumination"),
            (r"- Perpendicolari \(dot = 0\) → ombra", r"- Perpendicular (dot = 0) → shadow"),
            (r"- Opposti \(dot = -1\) → completamente in ombra", r"- Opposite (dot = -1) → completely in shadow"),
            (r"### Trasformazione View e Proiezione", r"### View Transformation and Projection"),
            (r"Applichiamo la matrice view per trasformare dal mondo allo spazio della camera.", r"We apply the view matrix to transform from world to camera space."),
            (r"Proiettiamo i vertici sullo schermo e salviamo anche lo shading.", r"We project the vertices on the screen and also save the shading."),
            (r"### Painter's Algorithm", r"### Painter's Algorithm"),
            (r"Ordiniamo i triangoli per profondità media \(Z\). Disegniamo prima quelli più lontani, poi quelli più vicini. Questo risolve \(parzialmente\) il problema dell'occlusione.", r"We sort the triangles by average depth (Z). We draw the furthest ones first, then the closest ones. This (partially) solves the occlusion problem."),
            (r"### Rendering dei Triangoli", r"### Triangle Rendering"),
            (r"Disegniamo ogni triangolo con un colore basato sullo shading:", r"We draw each triangle with a color based on its shading:"),
            (r"- Shading alto → bianco \(ben illuminato\)", r"- High shading → white (well lit)"),
            (r"- Shading basso → grigio scuro \(in ombra\)", r"- Low shading → dark gray (in shadow)"),
            (r"- Minimo 0.15 per avere sempre un po' di luce ambientale", r"- Minimum 0.15 to always have a bit of ambient light"),
            (r"## Concetti Chiave", r"## Key Concepts"),
            (r"### Pipeline di Rendering Completa", r"### Complete Rendering Pipeline"),
            (r"1. \*\*Spazio Locale\*\* → vertici del cubo originale", r"1. **Local Space** → vertices of the original cube"),
            (r"2. \*\*Spazio Mondo\*\* → dopo trasformazioni \(scala, rotazione, traslazione\)", r"2. **World Space** → after transformations (scale, rotation, translation)"),
            (r"3. \*\*Calcolo Normali\*\* → per back-face culling e illuminazione", r"3. **Normal Calculation** → for back-face culling and lighting"),
            (r"4. \*\*Spazio View\*\* → dal punto di vista della camera", r"4. **View Space** → from the camera's point of view"),
            (r"5. \*\*Spazio Schermo\*\* → dopo proiezione prospettica", r"5. **Screen Space** → after perspective projection"),
            (r"6. \*\*Sorting\*\* → ordina per profondità", r"6. **Sorting** → sort by depth"),
            (r"7. \*\*Rasterizzazione\*\* → disegna i triangoli", r"7. **Rasterization** → draw the triangles"),
            (r"Ottimizzazione: non disegniamo le facce che guardano lontano dalla camera. Dimezza il numero di triangoli da renderizzare!", r"Optimization: we don't draw faces that look away from the camera. Halves the number of triangles to render!"),
            (r"### Illuminazione Diffusa", r"### Diffuse Lighting"),
            (r"Il modello più semplice di illuminazione. L'intensità dipende dall'angolo tra luce e normale \(Legge di Lambert\).", r"The simplest lighting model. The intensity depends on the angle between light and normal (Lambert's Law)."),
            (r"Disegna gli oggetti dall'indietro verso davanti. Semplice ma non perfetto \(può fallire con triangoli intersecanti\).", r"Draws objects from back to front. Simple but not perfect (can fail with intersecting triangles)."),
            (r"## Provalo", r"## Try It Out"),
            (r"Vai su \[editor.p5js.org\]\(https://editor.p5js.org/\) e osserva il cubo illuminato che ruota! Nota come le facce cambiano luminosità in base all'orientamento rispetto alla luce.", r"Go to [editor.p5js.org](https://editor.p5js.org/) and watch the illuminated cube rotate! Note how the faces change brightness based on their orientation to the light.")
        ]
    },
    {
        "src": r"c:\Users\alecy\Desktop\coding\AlessandroBonomo28.github.io\_posts\2023-07-25-Scrivere-un-3d-engine-da-zero-tutorial-7.md",
        "dst": r"c:\Users\alecy\Desktop\coding\AlessandroBonomo28.github.io\_posts\2023-07-25-Scrivere-un-3d-engine-da-zero-tutorial-7-en.md",
        "replacements": [
            (r"lang: it", r"lang: en"),
            (r"lang_ref: 3d-engine-7", r"lang_ref: 3d-engine-7\npermalink: /en/posts/Scrivere-un-3d-engine-da-zero-tutorial-7/"),
            (r"alt: Clipping dei triangoli in p5.js", r"alt: Triangle clipping in p5.js"),
            (r"# Clipping dei Triangoli in p5.js", r"# Triangle Clipping in p5.js"),
            (r"## Cosa Facciamo", r"## What We're Doing"),
            (r"In questo tutorial risolviamo uno dei problemi più complessi della grafica 3D: il \*\*clipping\*\*! Quando un triangolo esce parzialmente dallo schermo o attraversa il piano near della camera, dobbiamo \"tagliarlo\" e creare nuovi triangoli. Senza clipping, i triangoli si deformano o scompaiono in modo errato.", r"In this tutorial we solve one of the most complex problems in 3D graphics: **clipping**! When a triangle partially exits the screen or crosses the camera's near plane, we must \"cut\" it and create new triangles. Without clipping, triangles deform or disappear incorrectly."),
            (r"## Il Codice Spiegato", r"## The Code Explained"),
            (r"### Funzioni Geometriche Base", r"### Basic Geometric Functions"),
            (r"Verifica se un punto è sopra \(o sul\) un piano. Un piano è definito da:", r"Checks if a point is above (or on) a plane. A plane is defined by:"),
            (r"- Un punto sul piano \(`planePoint`\)", r"- A point on the plane (`planePoint`)"),
            (r"- La normale \(perpendicolare\) al piano \(`planeNormal`\)", r"- The normal (perpendicular) to the plane (`planeNormal`)"),
            (r"Usa il dot product per calcolare la distanza firmata dal piano.", r"Uses the dot product to calculate the signed distance from the plane."),
            (r"### Intersezione con un Piano", r"### Plane Intersection"),
            (r"Calcola dove una linea \(da `vOrigin` nella direzione `vDirection`\) interseca un piano. Usa la formula parametrica della retta: `P = vOrigin \+ t \* vDirection`.", r"Calculates where a line (from `vOrigin` in the direction `vDirection`) intersects a plane. Uses the parametric line equation: `P = vOrigin + t * vDirection`."),
            (r"### Clipping di un Triangolo", r"### Clipping a Triangle"),
            (r"Prima classifichiamo ogni vertice del triangolo: è dentro o fuori dal piano?", r"First we classify each vertex of the triangle: is it inside or outside the plane?"),
            (r"#### Caso 1: Tutti Fuori \(insideCount = 0\)", r"#### Case 1: All Outside (insideCount = 0)"),
            (r"Il triangolo è completamente fuori → lo eliminiamo.", r"The triangle is completely outside → we remove it."),
            (r"#### Caso 2: Tutti Dentro \(insideCount = 3\)", r"#### Case 2: All Inside (insideCount = 3)"),
            (r"Il triangolo è completamente dentro → lo manteniamo com'è.", r"The triangle is completely inside → we keep it as it is."),
            (r"#### Caso 3: Un Vertice Dentro \(insideCount = 1\)", r"#### Case 3: One Vertex Inside (insideCount = 1)"),
            (r"Due vertici fuori, uno dentro → creiamo un \*\*triangolo più piccolo\*\*:", r"Two vertices outside, one inside → we create a **smaller triangle**:"),
            (r"- Manteniamo il vertice interno", r"- We keep the inner vertex"),
            (r"- Troviamo dove i due lati intersecano il piano", r"- We find where the two sides intersect the plane"),
            (r"- Creiamo un nuovo triangolo con questi tre punti", r"- We create a new triangle with these three points"),
            (r"#### Caso 4: Due Vertici Dentro \(insideCount = 2\)", r"#### Case 4: Two Vertices Inside (insideCount = 2)"),
            (r"Un vertice fuori, due dentro → creiamo un \*\*quad \(quadrilatero\)\*\* che poi dividiamo in \*\*due triangoli\*\*:", r"One vertex outside, two inside → we create a **quad (quadrilateral)** which we then divide into **two triangles**:"),
            (r"- Troviamo dove i lati intersecano il piano", r"- We find where the sides intersect the plane"),
            (r"- Creiamo due triangoli che coprono l'area dentro al piano", r"- We create two triangles that cover the area inside the plane"),
            (r"### Clipping Near Plane", r"### Near Plane Clipping"),
            (r"Dopo la trasformazione view, clippiamo contro il \*\*piano near\*\* della camera \(z = 0.01\). Questo impedisce che triangoli dietro la camera causino problemi di proiezione.", r"After the view transformation, we clip against the camera's **near plane** (z = 0.01). This prevents triangles behind the camera from causing projection issues."),
            (r"### Clipping Screen Space", r"### Screen Space Clipping"),
            (r"Dopo la proiezione, clippiamo contro i \*\*4 bordi dello schermo\*\*:", r"After projection, we clip against the **4 screen edges**:"),
            (r"- \*\*Left\*\* \(sinistra\): x = 0", r"- **Left**: x = 0"),
            (r"- \*\*Right\*\* \(destra\): x = width", r"- **Right**: x = width"),
            (r"- \*\*Top\*\* \(alto\): y = 0", r"- **Top**: y = 0"),
            (r"- \*\*Bottom\*\* \(basso\): y = height", r"- **Bottom**: y = height"),
            (r"Per ogni piano:", r"For each plane:"),
            (r"1. Prendiamo tutti i triangoli nella coda", r"1. We take all triangles in the queue"),
            (r"2. Li clippiamo uno per uno", r"2. We clip them one by one"),
            (r"3. I triangoli risultanti vengono rimessi nella coda", r"3. The resulting triangles are put back in the queue"),
            (r"4. Passiamo al piano successivo", r"4. We move to the next plane"),
            (r"Un triangolo può essere clippato più volte, creando fino a 8-9 triangoli!", r"A triangle can be clipped multiple times, creating up to 8-9 triangles!"),
            (r"Disegniamo tutti i triangoli risultanti dal clipping.", r"We draw all the triangles resulting from clipping."),
            (r"## Concetti Chiave", r"## Key Concepts"),
            (r"### Perché Serve il Clipping\?", r"### Why is Clipping Needed?"),
            (r"Senza clipping:", r"Without clipping:"),
            (r"- Triangoli dietro la camera si proiettano male \(divisione per z negativo!\)", r"- Triangles behind the camera project poorly (division by negative z!)"),
            (r"- Triangoli fuori dallo schermo sprecano risorse", r"- Triangles outside the screen waste resources"),
            (r"- Artefatti visivi quando un triangolo è parzialmente visibile", r"- Visual artifacts when a triangle is partially visible"),
            (r"### Sutherland-Hodgman Algorithm", r"### Sutherland-Hodgman Algorithm"),
            (r"L'algoritmo usato per il clipping screen-space. Clippa un poligono contro un piano alla volta, creando nuovi vertici dove necessario.", r"The algorithm used for screen-space clipping. Clips a polygon against one plane at a time, creating new vertices where necessary."),
            (r"### Pipeline Completa di Clipping", r"### Complete Clipping Pipeline"),
            (r"1. \*\*View Space\*\*: clipping contro piano near \(z = 0.01\)", r"1. **View Space**: clipping against the near plane (z = 0.01)"),
            (r"2. \*\*Projection\*\*: trasformazione prospettica", r"2. **Projection**: perspective transformation"),
            (r"3. \*\*Screen Space\*\*: clipping contro i 4 bordi dello schermo", r"3. **Screen Space**: clipping against the 4 screen edges"),
            (r"### Casi di Clipping", r"### Clipping Cases"),
            (r"Ogni piano può generare:", r"Each plane can generate:"),
            (r"- \*\*0 triangoli\*\*: tutti fuori", r"- **0 triangles**: all outside"),
            (r"- \*\*1 triangolo\*\*: tutti dentro O solo 1 vertice dentro", r"- **1 triangle**: all inside OR only 1 vertex inside"),
            (r"- \*\*2 triangoli\*\*: 2 vertici dentro \(forma quad\)", r"- **2 triangles**: 2 vertices inside (forms a quad)"),
            (r"## Provalo", r"## Try It Out"),
            (r"Vai su \[editor.p5js.org\]\(https://editor.p5js.org/\) e copia e incolla il codice:", r"Go to [editor.p5js.org](https://editor.p5js.org/) and copy and paste the code:"),
            (r"- Avvicinati molto al cubo \(premi W\)", r"- Get very close to the cube (press W)"),
            (r"- Osserva come i triangoli vengono tagliati correttamente quando escono dallo schermo", r"- Watch how the triangles are cut correctly when they exit the screen"),
            (r"- Senza clipping, vedresti artefatti strani!", r"- Without clipping, you would see strange artifacts!")
        ]
    },
    {
        "src": r"c:\Users\alecy\Desktop\coding\AlessandroBonomo28.github.io\_posts\2023-07-28-Scrivere-un-3d-engine-da-zero-tutorial-8.md",
        "dst": r"c:\Users\alecy\Desktop\coding\AlessandroBonomo28.github.io\_posts\2023-07-28-Scrivere-un-3d-engine-da-zero-tutorial-8-en.md",
        "replacements": [
            (r"lang: it", r"lang: en"),
            (r"lang_ref: 3d-engine-8", r"lang_ref: 3d-engine-8\npermalink: /en/posts/Scrivere-un-3d-engine-da-zero-tutorial-8/"),
            (r"alt: Importare modelli 3D in formato OBJ in p5.js", r"alt: Importing 3D models in OBJ format in p5.js"),
            (r"# Importare Modelli 3D \(OBJ\) in p5.js", r"# Importing 3D Models (OBJ) in p5.js"),
            (r"## Cosa Facciamo", r"## What We're Doing"),
            (r"In questo tutorial finale portiamo il nostro motore 3D al livello successivo: importiamo \*\*modelli 3D reali\*\* nel formato OBJ! Creiamo un parser che legge file .obj e li converte in triangoli renderizzabili dal nostro engine. Ora possiamo caricare qualsiasi modello 3D!", r"In this final tutorial we take our 3D engine to the next level: we import **real 3D models** in OBJ format! We create a parser that reads .obj files and converts them into triangles renderable by our engine. Now we can load any 3D model!"),
            (r"## I Due Script", r"## The Two Scripts"),
            (r"### objImporter.js - Il Parser", r"### objImporter.js - The Parser"),
            (r"Questo script definisce una classe che legge e interpreta file OBJ.", r"This script defines a class that reads and interprets OBJ files."),
            (r"Nel costruttore:", r"In the constructor:"),
            (r"- Creiamo un input per selezionare file", r"- We create an input to select files"),
            (r"- Usiamo `FileReader` per leggere il file come testo", r"- We use `FileReader` to read the file as text"),
            (r"- Quando il file è caricato, lo passiamo al parser", r"- When the file is loaded, we pass it to the parser"),
            (r"### Parsing dei Dati", r"### Data Parsing"),
            (r"Dividiamo il file OBJ in righe \(separate da `\\n`\) e processiamo ogni riga.", r"We divide the OBJ file into lines (separated by `\\n`) and process each line."),
            (r"### Parsing dei Vertici", r"### Vertex Parsing"),
            (r"Una riga tipo `v 1.0 0.5 -0.3` definisce un vertice. Separiamo per spazi e salviamo le coordinate nell'array `vertici`.", r"A line like `v 1.0 0.5 -0.3` defines a vertex. We split by spaces and save the coordinates in the `vertici` array."),
            (r"### Parsing delle Facce", r"### Face Parsing"),
            (r"Una riga tipo `f 1 2 3` o `f 1/1/1 2/2/2 3/3/3` definisce una faccia \(triangolo\).", r"A line like `f 1 2 3` or `f 1/1/1 2/2/2 3/3/3` defines a face (triangle)."),
            (r"- I numeri si riferiscono agli indici dei vertici \(base-1\)", r"- The numbers refer to the vertex indices (base-1)"),
            (r"- Se c'è `/`, prendiamo solo il primo numero \(indice vertice\)", r"- If there is a `/`, we take only the first number (vertex index)"),
            (r"- Recuperiamo le coordinate dai vertici salvati e creiamo un triangolo", r"- We retrieve the coordinates from the saved vertices and create a triangle"),
            (r"### Identificazione delle Righe", r"### Line Identification"),
            (r"Ogni riga OBJ inizia con un prefisso:", r"Each OBJ line starts with a prefix:"),
            (r"- `v` → vertice \(coordinate x,y,z\)", r"- `v` → vertex (x,y,z coordinates)"),
            (r"- `vn` → normale \(ignorata\)", r"- `vn` → normal (ignored)"),
            (r"- `vt` → texture coordinate \(ignorata\)", r"- `vt` → texture coordinate (ignored)"),
            (r"- `f` → faccia \(triangolo\)", r"- `f` → face (triangle)"),
            (r"Processiamo solo `v` e `f`.", r"We only process `v` and `f`."),
            (r"### sketch.js - Il Rendering", r"### sketch.js - The Rendering"),
            (r"Il file principale ora usa l'importer invece di triangoli hardcoded:", r"The main file now uses the importer instead of hardcoded triangles:"),
            (r"Quando `objImporter.importDone` è true, copiamo i triangoli importati nell'array `triangles` e il nostro engine li renderizza!", r"When `objImporter.importDone` is true, we copy the imported triangles into the `triangles` array and our engine renders them!"),
            (r"### Controlli Extra", r"### Extra Controls"),
            (r"Premendo \*\*H\*\* possiamo nascondere i punti e i bordi dei triangoli per vedere solo le facce solide.", r"By pressing **H** we can hide the points and edges of the triangles to see only the solid faces."),
            (r"## Il Formato OBJ", r"## The OBJ Format"),
            (r"Un file OBJ è un formato testo semplice:", r"An OBJ file is a plain text format:"),
            (r"- `v x y z` → definisce un vertice", r"- `v x y z` → defines a vertex"),
            (r"- `f i1 i2 i3` → definisce un triangolo usando gli indici dei vertici", r"- `f i1 i2 i3` → defines a triangle using vertex indices"),
            (r"- Gli indici partono da 1 \(non da 0!\)", r"- Indices start from 1 (not 0!)"),
            (r"Formati più complessi possono includere:", r"More complex formats can include:"),
            (r"- `f 1/1/1 2/2/2 3/3/3` → vertice/texture/normale", r"- `f 1/1/1 2/2/2 3/3/3` → vertex/texture/normal"),
            (r"- Facce con 4\+ vertici \(quad\) → il nostro parser li considera come un solo \"triangolo\" che verrà poi gestito dal clipping", r"- Faces with 4+ vertices (quads) → our parser considers them as a single \"triangle\" which will then be handled by clipping"),
            (r"## Pipeline Completa", r"## Complete Pipeline"),
            (r"1. \*\*Upload\*\*: l'utente seleziona un file .obj", r"1. **Upload**: the user selects an .obj file"),
            (r"2. \*\*Parsing\*\*: `ObjImporter` legge vertici e facce", r"2. **Parsing**: `ObjImporter` reads vertices and faces"),
            (r"3. \*\*Conversione\*\*: i dati OBJ diventano array di triangoli", r"3. **Conversion**: OBJ data becomes an array of triangles"),
            (r"4. \*\*Rendering\*\*: il nostro engine 3D renderizza i triangoli con:", r"4. **Rendering**: our 3D engine renders the triangles with:"),
            (r"   - Trasformazioni \(rotazione, scala, traslazione\)", r"   - Transformations (rotation, scale, translation)"),
            (r"   - Illuminazione", r"   - Lighting"),
            (r"   - Proiezione prospettica", r"   - Perspective projection"),
            (r"## Concetti Chiave", r"## Key Concepts"),
            (r"### File Reader API", r"### File Reader API"),
            (r"JavaScript può leggere file locali usando `FileReader`:", r"JavaScript can read local files using `FileReader`:"),
            (r"### Indicizzazione Vertici", r"### Vertex Indexing"),
            (r"Invece di duplicare coordinate, OBJ usa \*\*indici\*\*:", r"Instead of duplicating coordinates, OBJ uses **indices**:"),
            (r"- I vertici sono definiti una volta", r"- Vertices are defined once"),
            (r"- Le facce referenziano i vertici per indice", r"- Faces reference vertices by index"),
            (r"- Risparmia spazio e memoria", r"- Saves space and memory"),
            (r"### Triangolazione", r"### Triangulation"),
            (r"Molti modelli hanno quad \(4 vertici\). Il nostro parser li tratta come array più lunghi che il sistema di clipping può poi gestire.", r"Many models have quads (4 vertices). Our parser treats them as longer arrays that the clipping system can then handle."),
            (r"## Provalo", r"## Try It Out"),
            (r"1. Vai su \[editor.p5js.org\]\(https://editor.p5js.org/\)", r"1. Go to [editor.p5js.org](https://editor.p5js.org/)"),
            (r"2. Crea due file: `sketch.js` e `objImporter.js`", r"2. Create two files: `sketch.js` and `objImporter.js`"),
            (r"3. Copia il codice in entrambi i file", r"3. Copy the code into both files"),
            (r"4. Scarica un modello .obj semplice \(es. da \[qui\]\(https://github.com/AlessandroBonomo28/Elegoo-TouchScreen-2.8-GFX-fun/tree/base/p5%20js%20testing/youtube/obj%20files\)\)", r"4. Download a simple .obj model (e.g. from [here](https://github.com/AlessandroBonomo28/Elegoo-TouchScreen-2.8-GFX-fun/tree/base/p5%20js%20testing/youtube/obj%20files))"),
            (r"5. Premi play e seleziona il file .obj", r"5. Press play and select the .obj file"),
            (r"6. Guarda il tuo modello renderizzato in 3D!", r"6. Watch your 3D model rendered in 3D!"),
            (r"Controlli:", r"Controls:"),
            (r"- \*\*WASD\*\* → movimento", r"- **WASD** → movement"),
            (r"- \*\*Mouse drag\*\* → guarda in giro", r"- **Mouse drag** → look around"),
            (r"- \*\*Spazio/Shift\*\* → su/giù", r"- **Space/Shift** → up/down"),
            (r"- \*\*H\*\* → nascondi/mostra wireframe", r"- **H** → hide/show wireframe"),
            (r"- \*\*T\*\* → mostra/nascondi coordinate", r"- **T** → show/hide coordinates"),
            (r"### Il codice intero", r"### The full code"),
            (r"Ecco qui `objImporter.js`:", r"Here is `objImporter.js`:"),
            (r"Ecco qui `sketch.js`:", r"Here is `sketch.js`:")
        ]
    }
]

for item in files_to_process:
    with open(item['src'], 'r', encoding='utf-8') as f:
        content = f.read()
    
    for old, new in item['replacements']:
        content = re.sub(old, new, content)
        
    with open(item['dst'], 'w', encoding='utf-8') as f:
        f.write(content)

print("Translation done.")
